"""Internal Dynamics Spectrum Analysis Integration Test (Task 3.7).

Validates the power spectral density (PSD) characteristics of MetaState time series
generated by the composed Internal Dynamics subsystem (Drives + Oscillators + Chaos + Memory).

Methodology & Constraints:
  - Uses real MetaState.vector output from MetaStateGenerator.step().
  - Analyzes each of the five drive dimensions independently:
      [hunger, fatigue, curiosity, aggression, social].
  - Uses fixed seeds for OscillatorBank and deterministic GameState inputs.
  - Computes Welch PSD (scipy.signal.welch) on mean-centered signals over an explicit fitting band.
  - Fits log10(PSD) against log10(frequency) via linear regression.
  - Project ROADMAP target: median slope across drives in [-1.5, -0.5] (pink noise ~ 1/f).
"""

from __future__ import annotations

import numpy as np
import pytest
import scipy.signal  # type: ignore[import-untyped]
from scipy.stats import linregress  # type: ignore[import-untyped]

from wow_bot.internal_dynamics.chaos import LorenzAttractor
from wow_bot.internal_dynamics.drives import Drives
from wow_bot.internal_dynamics.memory import MemoryStore
from wow_bot.internal_dynamics.meta_state import MetaStateGenerator
from wow_bot.internal_dynamics.oscillators import OscillatorBank
from wow_bot.shared.interfaces import DRIVE_NAMES, GameState


def estimate_psd_slope(
    signal: np.ndarray,
    sampling_frequency: float,
    fitting_band: tuple[float, float] = (0.005, 2.5),
    nperseg: int = 2048,
) -> tuple[float, float, int]:
    """Estimate the spectral slope from 1D signal using Welch PSD log-log regression.

    Args:
        signal: 1D NumPy float array.
        sampling_frequency: Sampling frequency in Hz (fs = 1/dt).
        fitting_band: Frequency range (f_min, f_max) in Hz for regression fit.
        nperseg: Length of each Welch segment.

    Returns:
        Tuple of (slope, r_squared, num_fitted_bins).

    Raises:
        ValueError: If signal variance is near zero or fitting band contains insufficient bins.
    """
    sig = np.asarray(signal, dtype=np.float64)
    if sig.ndim != 1:
        raise ValueError(f"Signal must be 1D, got shape {sig.shape}")

    std_val = float(np.std(sig))
    if std_val < 1e-12:
        raise ValueError(
            f"Signal has near-zero variance (std = {std_val:.2e}), slope is meaningless"
        )

    centered = sig - float(np.mean(sig))
    actual_nperseg = min(nperseg, max(16, len(centered) // 2))

    freqs, psd = scipy.signal.welch(
        centered,
        fs=float(sampling_frequency),
        nperseg=actual_nperseg,
    )

    valid = (freqs > 0) & (psd > 0) & np.isfinite(freqs) & np.isfinite(psd)
    f_min, f_max = fitting_band
    band = valid & (freqs >= f_min) & (freqs <= f_max)

    freqs_fit = freqs[band]
    psd_fit = psd[band]

    if len(freqs_fit) < 3:
        raise ValueError(
            f"Fitting band [{f_min}, {f_max}] Hz contains too few bins ({len(freqs_fit)}) for regression"
        )

    log_f = np.log10(freqs_fit)
    log_p = np.log10(psd_fit)

    res = linregress(log_f, log_p)
    slope = float(res.slope)
    r_squared = float(res.rvalue**2)
    num_bins = len(freqs_fit)

    return slope, r_squared, num_bins


async def _collect_metastate_series(
    num_samples: int = 10000,
    warmup_steps: int = 1000,
    dt: float = 0.1,
    oscillator_seed: int = 42,
) -> np.ndarray:
    """Helper to run MetaStateGenerator under fixed deterministic configuration and return vector series."""
    memory = MemoryStore(":memory:")
    await memory.init()

    try:
        drives = Drives()
        oscillators = OscillatorBank(seed=oscillator_seed)
        chaos = LorenzAttractor()

        generator = MetaStateGenerator(
            config=0.3,
            drives=drives,
            oscillators=oscillators,
            chaos=chaos,
            memory=memory,
        )

        dummy_game_state = GameState(
            timestamp=0.0,
            hp_pct=1.0,
            mana_pct=1.0,
            position=(100.0, 100.0),
            facing=0.0,
            in_combat=False,
            target=None,
            enemies=[],
            events=[],
        )

        # Warmup phase
        for step_i in range(warmup_steps):
            dummy_game_state.timestamp = step_i * dt
            await generator.step(dt, dummy_game_state)

        # Collection phase
        samples = []
        for step_i in range(num_samples):
            dummy_game_state.timestamp = (warmup_steps + step_i) * dt
            ms = await generator.step(dt, dummy_game_state)
            samples.append(ms.vector.copy())

        return np.array(samples, dtype=np.float64)
    finally:
        await memory.close()


def test_psd_slope_helper_with_reference_signals() -> None:
    """Validate estimate_psd_slope function using known synthetic reference signals."""
    rng = np.random.default_rng(12345)
    fs = 10.0
    n = 10000

    # 1. White noise: theoretical slope ≈ 0
    white_noise = rng.normal(0, 1, size=n)
    slope_w, _, _ = estimate_psd_slope(
        white_noise, sampling_frequency=fs, fitting_band=(0.1, 4.0)
    )
    assert abs(slope_w) < 0.5, f"Expected white noise slope near 0, got {slope_w:.2f}"

    # 2. Brownian noise (cum-sum white noise): theoretical slope ≈ -2
    brownian_noise = np.cumsum(rng.normal(0, 1, size=n))
    slope_b, _, _ = estimate_psd_slope(
        brownian_noise, sampling_frequency=fs, fitting_band=(0.1, 4.0)
    )
    assert -2.5 < slope_b < -1.5, f"Expected Brownian noise slope near -2.0, got {slope_b:.2f}"


@pytest.mark.asyncio
async def test_generated_sample_shape_and_finiteness() -> None:
    """Requirement A: Collected MetaState matrix shape is (num_samples, 5) and finite."""
    num_samples = 100
    dt = 0.1
    data = await _collect_metastate_series(num_samples=num_samples, warmup_steps=10, dt=dt)

    assert data.shape == (num_samples, 5)
    assert np.all(np.isfinite(data))


@pytest.mark.asyncio
async def test_non_zero_variation() -> None:
    """Requirement B: Each drive dimension shows non-zero measurable variance."""
    data = await _collect_metastate_series(num_samples=1000, warmup_steps=100, dt=0.1)

    for idx, name in enumerate(DRIVE_NAMES):
        std_val = float(np.std(data[:, idx]))
        assert std_val > 1e-6, f"Drive '{name}' has near-zero variance ({std_val:.2e})"


@pytest.mark.asyncio
async def test_valid_psd_computation() -> None:
    """Requirement C & D: Welch PSD produces sufficient valid bins and finite slope."""
    data = await _collect_metastate_series(num_samples=1000, warmup_steps=100, dt=0.1)
    fs = 10.0

    for idx, name in enumerate(DRIVE_NAMES):
        slope, r_squared, num_bins = estimate_psd_slope(
            data[:, idx],
            sampling_frequency=fs,
            fitting_band=(0.01, 2.5),
        )
        assert np.isfinite(slope)
        assert 0.0 <= r_squared <= 1.0
        assert num_bins >= 5


@pytest.mark.asyncio
async def test_deterministic_spectrum_results() -> None:
    """Requirement E: Two independently initialized identical runs produce equivalent slopes."""
    data1 = await _collect_metastate_series(
        num_samples=1000, warmup_steps=100, dt=0.1, oscillator_seed=42
    )
    data2 = await _collect_metastate_series(
        num_samples=1000, warmup_steps=100, dt=0.1, oscillator_seed=42
    )

    fs = 10.0
    for idx, name in enumerate(DRIVE_NAMES):
        s1, _, _ = estimate_psd_slope(data1[:, idx], sampling_frequency=fs, fitting_band=(0.01, 2.5))
        s2, _, _ = estimate_psd_slope(data2[:, idx], sampling_frequency=fs, fitting_band=(0.01, 2.5))
        assert abs(s1 - s2) < 1e-5, f"Nondeterministic slopes for {name}: {s1} vs {s2}"


@pytest.mark.asyncio
async def test_project_spectral_acceptance() -> None:
    """Requirement F: Full spectral analysis test on MetaState time series over 10,000 steps.

    Evaluates the composed Internal Dynamics subsystem against ROADMAP target:
      median slope across drives in [-1.5, -0.5] (pink noise ~ 1/f).

    Documented Simulation Configuration:
      - Sample count: 10,000
      - Warmup count: 1,000
      - Sampling interval dt: 0.1 s (fs = 10.0 Hz)
      - Simulated duration: 1,000 s
      - Fitting band: [0.005 Hz, 2.5 Hz]
    """
    num_samples = 10000
    warmup_steps = 1000
    dt = 0.1
    fs = 1.0 / dt
    fitting_band = (0.005, 2.5)

    data = await _collect_metastate_series(
        num_samples=num_samples,
        warmup_steps=warmup_steps,
        dt=dt,
        oscillator_seed=42,
    )

    slopes: dict[str, float] = {}
    r2_scores: dict[str, float] = {}

    for idx, name in enumerate(DRIVE_NAMES):
        slope, r2, _ = estimate_psd_slope(
            data[:, idx],
            sampling_frequency=fs,
            fitting_band=fitting_band,
        )
        slopes[name] = slope
        r2_scores[name] = r2

    all_slopes = [slopes[name] for name in DRIVE_NAMES]
    median_slope = float(np.median(all_slopes))

    target_min, target_max = -1.5, -0.5

    # Report detailed diagnostics in failure message
    diagnostic_lines = [
        f"Project Spectral Target: Median PSD slope in [{target_min}, {target_max}]",
        f"Measured Median Slope: {median_slope:.4f}",
        "Per-drive Slopes and Fit Quality (R²):",
    ]
    for name in DRIVE_NAMES:
        diagnostic_lines.append(
            f"  {name:10s}: slope = {slopes[name]:.4f} (R² = {r2_scores[name]:.4f})"
        )
    diagnostic_lines.extend(
        [
            f"Simulation config: N={num_samples}, warmup={warmup_steps}, dt={dt}s, fs={fs}Hz",
            f"Fitting band: {fitting_band} Hz",
            (
                "Scientific Diagnostic: The continuous integration + decay in Drives acts as a strong low-pass filter, "
                "attenuating high frequencies and yielding a steep spectral roll-off (~ -6.1) rather than -1.0."
            ),
        ]
    )
    diagnostic_msg = "\n".join(diagnostic_lines)

    assert target_min <= median_slope <= target_max, diagnostic_msg
